version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    networks:
      - yatda-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
    networks:
      - yatda-network

  # postgresql:
  #   image: postgres:14-alpine
  #   environment:
  #     - POSTGRES_DB=yatdapostgres
  #     - POSTGRES_USER=guest
  #     - POSTGRES_PASSWORD=guest
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - postgresqldata:/var/lib/postgresql/data
  #   networks:
  #     - yatda-network
volumes:
  mongodbdata:
  rabbitmqdata:
  # postgresqldata:

networks:
  yatda-network: